# Generated by Django 5.1.3 on 2024-12-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cientifico_Mundo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='validacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cientifico_Mundo.validacao'),
        ),
    ]
